### ISSUE TITLE
oauth2集成jwt不生效

### ISSUE THREAD

**Issue by VioletCoding** [dromara/Sa-Token#351]
### 使用版本: 
1.33.0

### 涉及的功能模块：
oauth2、jwt

### 测试步骤：
+ 我经过以下步骤测试：
引入sa-token-jwt，并添加以下配置：
```java
@Configuration
public class SaTokenConfigure {
    @Bean
    public StpLogic getStpLogicJwt() {
        return new StpLogicJwtForStateless();
    }
}
```

```java
    @RequestMapping("/oauth2/*")
    public Object oauth2() {
        return SaOAuth2Handle.serverRequest();
    }

    private final UserService userSvc;

    @Autowired
    public void setSaOauth2Config(SaOAuth2Config cfg) {
        cfg.setDoLoginHandle((username, password) -> {
            if (StrUtils.hasBlank(username, password)) {
                return false;
            }
            UserEntity user = userSvc.getOne(Wrappers
                    .<UserEntity>lambdaQuery()
                    .eq(UserEntity::getUsername, username)
                    .eq(UserEntity::getPassword, SecureUtil.md5(password)));
            if (user == null){
                return R.fail("用户名密码错误");
            }
            StpUtil.login(user.getId());
            return R.data("ok");
        });
    }
```

```yaml
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: test-token
  # token前缀
  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 开启oauth2
  oauth2:
    # 开启密码模式
    is-password: true
    # 开启授权码模式
    is-code: true
    # 开启凭证模式
    is-client: true
    # 隐式模式
    is-implicit: true
    # jwt秘钥
  jwt-secret-key: '21232f297a5zsd123123213aaaa801fc3'
  is-print: false
```
+ 请求以下接口：
`http://localhost:8080/oauth2/token?grant_type=password&client_id=smooth&username=admin&password=21232f297a57a5a743894a0e4a801fc3&client_secret=238bd4ec3f45825dd0ba58e96407f0fe&scope=*`

+ 得出以下结果：
```json
{
    "code": 200,
    "msg": "ok",
    "data": {
        "access_token": "QqrELZI8duw8uUHa4VW9lGxw41QcYLZ9KNwjzsoaTNh8f6fJqn7uYIrR0Z0t",
        "refresh_token": "4mZgOfAPpgjYc27ZLuRoQ2MlM3JbjBDq0R0JodGj27iZiif6dbVzUgNW0zKb",
        "expires_in": -2,
        "refresh_expires_in": -2,
        "client_id": "test",
        "scope": "*",
        "openid": "9za5s8a6as4d5z45s5s"
    }
}
```
+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：
我的预期是：获得jwt样式的token，也就是`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOjEsImRldmljZSI6ImRlZmF1bHQtZGV2aWNlIiwiZWZmIjoxNjczMTk0NzEzMDQ0LCJyblN0ciI6InBOWk1Oa0ZzMWZvWWlSSjdaNldDMENwN1NQclNOSlJ0In0.TOilEaG4H5eIHrH3Q6aduMcT0RIQ0iGGmSa7WZBu-VM`这样的token，debug的时候发现一直调用如下方法，并没有使用jwt：
![image](https://user-images.githubusercontent.com/37135917/206746447-c701700f-c959-44ac-a35b-6a9df5153d1e.png)
![image](https://user-images.githubusercontent.com/37135917/206746499-d696961d-ca51-4ea9-98ea-3f7fe2d7d2ff.png)
但是控制台打印的日志是我想要的：
![image](https://user-images.githubusercontent.com/37135917/206746829-b4afe0f5-8cfd-4cba-b680-e080672d689b.png)

+ 我的理解是：
之前项目用的是SpringSecurity，同样也是用的OAuth2的密码模式来登录，我的预期是这个jwt不应该是全局替换掉这个随机生成token的方法为用jwt吗？是我哪里配错了？刚使用SaToken，如果有遗漏还请指出，谢谢！

请问，是我的理解不对，还是文档出了问题？
