### ISSUE TITLE
配置redis的database不生效

### ISSUE THREAD

**Issue by heyyuyu** [dromara/Sa-Token#391]
### 测试步骤：
+ 我经过以下步骤测试：
在application.yaml中同时配置了业务redis和sa-token的redis，但是sa-token中指定的database不生效，配置如下：
```
spring:
  redis:
    database: 0
    host: *****
    port: 6379
    password: ******
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
sa-token:
  token-name: iastoken
  timeout: 86400
  activity-timeout: 3600
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  alone-redis:
    database: 1
    host: *****
    port: 6379
    password: ******
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
```
+ 得出以下结果：

在登录后发现sa-token的缓存到了db0上

+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：

+ 我的理解是：
应该是配置了sa-token的database为1，缓存到db1上面

请问，是我的理解不对，还是文档出了问题？
