### ISSUE TITLE
集成Redis后项目无法启动

### ISSUE THREAD

**Issue by YoungTakhin** [dromara/Sa-Token#459]
### 对以下问题有疑问:

SpringBoot3 集成 MongoDB 和 Redis后项目无法启动，依赖如下：

```XML
    <dependency>
      <groupId>cn.dev33</groupId>
      <artifactId>sa-token-spring-boot3-starter</artifactId>
      <version>1.34.0</version>
    </dependency>

    <dependency>
      <groupId>cn.dev33</groupId>
      <artifactId>sa-token-dao-redis-jackson</artifactId>
      <version>1.34.0</version>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-pool2</artifactId>
    </dependency>
```

配置文件如下：

```yml
spring:
  data:
    mongodb:
      uri: mongodb://xxxx
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
      repositories:
        type: imperative
    redis:
      database: 8
      host: xxx
      port: xxx
      password: xxx
      timeout: 1000ms
      lettuce:
        pool:
          max-active: 255
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
```

项目启动后控制台报如下错误：

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method mongoTemplate in org.springframework.boot.autoconfigure.data.mongo.MongoDatabaseFactoryDependentConfiguration required a single bean, but 2 were found:
	- mongoCustomConversions: defined by method 'mongoCustomConversions' in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDataConfiguration.class]
	- redisCustomConversions: defined in unknown location


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

请问是不是我有哪步弄错了？
