### ISSUE TITLE
使用springboot3.x整合Sa-Token和Knife4j 4.x时出现swagger被拦截

### ISSUE THREAD

**Issue by Poison02** [dromara/Sa-Token#462]
### 使用版本:
`pom.xml`: 
```xml
<dependency>
       <groupId>cn.dev33</groupId>
       <artifactId>sa-token-spring-boot3-starter</artifactId>
       <version>1.34.0</version>
</dependency>
<dependency>
      <groupId>com.github.xiaoymin</groupId>
      <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
      <version>4.1.0</version>
</dependency>
```
---
`application.yml`:
```yml
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cdu.icu.oos
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
```
---
`SaTokenConfig.java`:
```java
@Configuration
public class SaTokenConfig implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        // 注册 Sa-Token 拦截器，校验规则为 StpUtil.checkLogin() 登录校验。
        registry.addInterceptor(new SaInterceptor(handle -> StpUtil.checkLogin()))
                .addPathPatterns("/**")
                .excludePathPatterns("/api/user/login")
                .excludePathPatterns("/api/user/register")
                .excludePathPatterns(
                        "/**/doc.*",
                        "/**/swagger-ui.*",
                        "/**/swagger-resources",
                        "/**/webjars/**",
                        "/**/v3/api-docs/**"
                );
    }
}
```

### 报错信息：
当我访问：`localhost:8080/swagger-ui.html`时触发异常
![image](https://github.com/dromara/Sa-Token/assets/106656220/25e07827-da73-4b0d-8109-b4748c1ab7fc)

### 希望结果：
希望能看到swagger文档

### 复现步骤：
1. 添加pom依赖
2. 增加application.yml配置
3. 增加拦截器配置

< 备注：如果复现步骤比较复杂，请将 demo 上传到 gitee 并留下地址 >
