### ISSUE TITLE
登录验证有问题

### ISSUE THREAD

**Issue by MrCh1ppy** [dromara/Sa-Token#591]
### 使用版本:

        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-spring-boot3-starter</artifactId>
            <version>1.37.0</version>
        </dependency>
        
        <dependency>
            <groupId>cn.dev33</groupId>
            <artifactId>sa-token-redis</artifactId>
            <version>1.37.0</version>
        </dependency>

### 涉及的功能模块：
@SaCheckLogin
Stputils.checkLogin()

### 测试步骤：
+ 我经过以下步骤测试：
我的代码如下：
```java
	@PostMapping("/query/page")
	@Operation(summary = "用户查询")
	public ApiResult<Page<UserVo>> queryInPage(@Validated @RequestBody QueryUserReq req){
		StpUtil.checkLogin();

		final var query = userService.query(req);
		return ApiResult.ok(query);
	}
```
我的配置项如下
```yaml
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
```
+ 得出以下结果：
登录时可以返回tokenValue是一切正常的
但是在上文的接口中，虽然加了StpUtils.checkLogin（），但是不加header还是可以访问，且不报错。另外上文的接口我也试过@SaCheckLogin这个注解，效果是一致的

+ 其中第 xx 行的代码输出表现 和文档上描述的不一致：
“StpUtil.checkLogin();”主要就是这个代码，其没有抛出异常。

+ 我的理解是：
可能是redis的token在不同的运行时发生了混淆？或者出了bug

请问，是我的理解不对，还是文档出了问题？
