### ISSUE TITLE
在GateWay中使用SaReactorFilter，跨域配置失效

### ISSUE THREAD

**Issue by guanqing7011** [dromara/Sa-Token#613]
### 对以下问题有疑问:
在GateWay中使用SaReactorFilter，通过鉴权后，并没有返回响应的跨域响应头。如果将该过滤器注释，则没有跨域问题。
< 备注：请尽量详细描述问题所在 >
1. SaReactorFilter 配置类
``` java
    @Bean
    public SaReactorFilter getSaReactorFilter() {
        return new SaReactorFilter()
                // 拦截地址
                .addInclude("/**")    /* 拦截全部path */
                // 开放地址
                .addExclude("/favicon.ico")
                // swagger 相关
                .addExclude("/doc.html*/**", "/*/doc.html*/**","/*/v3/api-docs","/doc.html","/v3/api-docs/swagger-config")
                .addExclude("/webjars/**")
                .addExclude("/oauth*/**")
                // 鉴权方法：每次访问进入
                .setAuth(obj -> {
                    String requestPath = SaHolder.getRequest().getRequestPath();
                    List<String> notMatchPaths = getNotMatchPathByRedis(requestPath);
                    // 登录校验
                    new SaRouterStaff().match("/**")
                            .notMatch(notMatchPaths)
                            .check(r -> StpUtil.checkLogin());
                })
                .setError(e -> {
                    // 补充 Content-Type 和 跨域响应头
                    setCorsHeader();
                    CommonResult<Object> res = CommonResult.unauthorized();
                    return JSON.toJSONString(res);
                })
                ;
    }
```
2. yml配置
```yml
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            #这里有个allowCredentials: true这个东西是设置允许访问携带cookie的，这点一定要和前端对应！
            allowCredentials: true
            #  当前gateway版本中 当 allowedOrigins 为 * 时，allowCredentials 不能为 true 所以采用allowedOriginPatterns
            allowedOriginPatterns:
              - "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 360000
```
3. 依赖版本
spring-boot-starter-parent:3.2.4   
spring-cloud-starter-gateway:4.0.8
sa-token-reactor-spring-boot3-starter:1.37.0
sa-token-redis-jackson:1.37.0
