### ISSUE TITLE
配置了sa-token.token-prefix=Bearer，sa-token自动写入cookie值没有包含这个前缀？然后导致依赖cookie方式时StpLogic().isLogin()返回false

### ISSUE THREAD

**Issue by happyyangyuan** [dromara/Sa-Token#699]
### 使用版本:
1.39.0

### 涉及的功能模块：
sa-token-core（我的项目还使用了oauth2模块）

### 测试步骤：
+ 我的application.yml配置
````
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
````
服务器端使用StpUtil.login(userId)进行的登录。

+ 得出以下结果：
虽然实际上已经登录，token和cookie都有了，是Authorization=xxxx-xxxx-xxxx（没有“Bearer ”前缀），StpUtil.isLogin()返回false。
StpLogic.getTokenValueNotCut()返回token值没有Bearer前缀，StpLogic.getTokenValue()返回的是null。

+ 我的理解是：
是不是给Authorization cookie值加上前缀，就能解决？或者StpLogic.getTokenValueNotCut()返回token值没有Bearer前缀，就自动给拼上前缀？
